# Generated by Django 2.2.5 on 2019-10-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
